name: Scheduled Email

on:
  workflow_dispatch: {}
  schedule:
#   Eg: Runs at 04:00 UTC every day.
    - cron: '0 7 * * *'
  
jobs:
  email:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Node LTS versions
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          
      - name: Install Node.js dependencies
        run: |
          pnpm i --no-frozen-lockfile
        
      - env:
            SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
            SENDER_APP_PASSWORD: ${{ secrets.SENDER_APP_PASSWORD }}
            RECEIVING_EMAIL: ${{ secrets.RECEIVING_EMAIL }}
            NO_OF_HIGHLIGHTS: ${{ secrets.NO_OF_HIGHLIGHTS }}
        run: pnpm run start
